ecomshamsiya/ecom/cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns=[
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

ecomshamsiya/ecom/ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecomshamsiya/ecom/search_app/urls.py
from django.urls import path
from . import views
app_name='search_app'
urlpatterns=[
    path('',views.SearchResult,name='SearchResult'),
]

ecomshamsiya/ecom/shop/urls.py
from django.urls import path
from . import views
app_name='shop'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='alProdCat'),
    path('<slug:c_slug>/<slug:product_slug>/', views.prodCat, name='prodCat'),
]

ecomshamsiya/ecom/cart/models.py
from django.db import models
from shop.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return '{}'.format(self.product)

ecomshamsiya/ecom/search_app/models.py
from django.db import models

# Create your models here.

ecomshamsiya/ecom/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)
    
    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('shop:alProdCat',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def get_url(self):
        return reverse('shop:prodCat',args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

ecomshamsiya/ecom/cart/views.py
from django.shortcuts import render,redirect
from shop.models import Product
from . models import Cart,CartItem
from django.shortcuts import get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
def _cart_id(request):
    # return render(request,'products.html')
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity        
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity>1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecomshamsiya/ecom/search_app/views.py
from shop.models import Product
from django.shortcuts import render
from django.db.models import Q
# Create your views here.
def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

ecomshamsiya/ecom/shop/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from . models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.

def allProdCat(request,c_slug=None):
    c_page=None
    products=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products=Product.objects.all().filter(category=c_page,available=True)
    else:
        products=Product.objects.all().filter(available=True)
    paginator=Paginator(products,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,'category.html',{'category':c_page,'products':products})

def prodCat(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'products.html',{'products':product})

ecomshamsiya/ecom/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <meta name="description" content="{% block metadescription %}{% endblock %}">



 
  
  {% comment %} <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">  {% endcomment %}
  {% comment %} <script src="{% static 'js/popper.min.js' %}"></script> {% endcomment %}
  {% comment %} <script src="{% static 'js/bootstrap.min.js' %}"></script> {% endcomment %}
  
  {% comment %} <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,100&display=swap" rel="stylesheet"> {% endcomment %}
  {% comment %} <script src="https://kit.fontawesome.com/a076d05399.js"></script>  {% endcomment %}
<title>{% block title %}{% endblock %}</title>
  
</head>
<body>
<div>
{% include 'header.html' %}
{% include 'nav.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" 
crossorigin="anonymous"></script> 
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" 
integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" 
crossorigin="anonymous"></script> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" 
integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" 
crossorigin="anonymous"></script> 
</body>
</html>

ecomshamsiya/ecom/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
this is the cart page
{% endblock %}
{% block title %}
CART-ABC company 
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            your shopping cart is empty
        </h1>
        <br>
        <p class="text-center">
            please click <a href="{% url 'shop:allProdCat' %}">here</a>to continue shopping
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            your shopping cart
        </h1>
        <br>
    </div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        your items
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="#"><img src="{{cart_item.product.image.url}}" alt="" style="width:100px;height:100px;" class="float-left rounded custom_image"></a>
                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU:{{cart_item.product.id}}
                        <br>
                        price:${{cart_item.product.price}}
                        <br>
                        qty:{{cart_item.quantity}} x ${{cart_item}}
                    </td>
                    <td>
                        ${{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa fa-plus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                        {% else %}
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th>
                        checkout
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        please review your shopping cart items
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                        your total is: <strong> {{ total }} </strong>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="mx_auto">
            <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">continue shopping</a>
            <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">make payment</a>
        </div>
    </div>

</div>
{% endif %}
{% endblock %}

ecomshamsiya/ecom/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.description|truncatewords:155}}
    {% else %}
        THIS IS YOUR DESCRIPTION
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{category.name}}-ABC STORE
    {% else %}
        GOOD DAY-ABC STORE
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx-auto">
            <p><a href="{% url 'shop:allProdCat' %}">CLICK TO SEE OUR PRODUCTS</a></p>
            </div>
        </div>
    </div>
    {% endif %}
<div class="mx_auto">
    {% if category %}
    <img class="my_image" src="{{category.image.url}}">
</div>
<br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
    {% else %}
<div>
    <img src="{% static 'img/banner.png' %}" width="1800" height="700" alt="logimage"> 
</div>
<br>
<div>
    <h1 class="text-center my_title">VIEW OUR PRODUCTS</h1>
    <p class="text-justify">good day...</p>
</div>
{% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
                <div class="card text-center" style="min-width:18rem">
                    <a href="{{product.get_url}}"><img src="{{product.image.url}}"></a>
                <div class="card-body">
                    <h3>{{product.name}}</h3>
                    <p>{{product.price}}</p>
                </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="row mx_auto">
        {% if product.paginator.num_pages > 1 %}
        <div class="text-center">
        {% for pg in product.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if product.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
        </div>
        {% endif %}
    </div> 
</div>
{% endblock %}

ecomshamsiya/ecom/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
<p class="text-center">ALL COPYRIGHTS RESERVED</p>
</div>

ecomshamsiya/ecom/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shop:allProdCat' %}"> <img src="{% static 'img/logo.png' %}" width="100" height="100" alt="logimage"> </a>
    </center>
</header>

ecomshamsiya/ecom/templates/nav.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">HOME</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">contact
          </a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a></li>
            {% for cat in link %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

ecomshamsiya/ecom/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    
    {{products.description|truncatewords:155}}
    
{% endblock %}
{% block title %}

    {{products.name}}-ABC STORE

{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shop:allProdCat' %}">HOME</a>|<a href="{{products.category.get_url}}">{{products.category}}</a>|{{products.name}}</p>
    </div>
<div class="container">
<br>        
<div class="row">   
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{products.image.url}}">
        </div>
    </div>

    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <h1 class="my_prod_title">{{products.name}}</h1>
        <p>${{products.price}}</p>
        <p class="my_title">product description</p>
        <p class="text-justify my_rod_text">{{products.description}}</p>
        {% if products.stock <= 0 %}
        <p class="text-justify my_prod_text">out of stock</p>
        {% else %}
        <a class="btn btn-secondary" href="{% url 'cart:add_cart' products.id %}">ADD TO CART</a>
        {% endif %}
    </div>
</div>
</div>
</div>
{% endblock %}

ecomshamsiya/ecom/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
we have variety of products
{% endblock %}
{% block title %}
search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">you have searched for:<b>"{{query}}"</p>
</div>

<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
            <div class="card text-center" style=".....">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.img.url}}" width="100" height="100">
            <div class="card-body">
                <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
            </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found</p>
        </div>
        {% endfor %}   
    </div>
</div>
{% endblock %}